workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  PHP_IMAGE: $CI_REGISTRY_IMAGE/demo:1.0.0

stages:
  - build
  - test
  - preparation
  - review

build:
  stage: build
  image: $PHP_IMAGE
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: push
  tags:
    - docker
  script:
    - composer config -g http-basic.gitlab.cern.ch $GIT_USERNAME $GIT_PASSWORD
    - composer install  --no-interaction --prefer-dist

test:
  stage: test
  image: $PHP_IMAGE
  services:
    - redis:4.0
    - schickling/mailcatcher
  tags:
    - docker
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  script:
    - ./vendor/bin/phpunit --testdox