workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  PHP_IMAGE: gitlab-registry.cern.ch/fence/atlas/php-7.3.27:0.1.0
  STAGING_RELEASES_PATH: /srv/glance-project/releases

.vendor-check:
  before_script: &vendor-check
    - .gitlab/ci/check-vendor.sh

stages:
  - build
  - test
  - preparation
  - review

build-composer-dependencies:
  stage: build
  image: $PHP_IMAGE
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: push
  tags:
    - docker
  script:
    - composer config -g http-basic.gitlab.cern.ch $GIT_USERNAME $GIT_PASSWORD
    - composer install  --no-interaction --prefer-dist

build-node-dependencies:
  stage: build
  image: node:12-slim
  tags:
    - docker
  script:
    - npm ci
    - npm ls

run-tests:
  stage: test
  image: $PHP_IMAGE
  tags:
    - docker
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  before_script: *vendor-check
  script:
    - composer test

deploy-review-app:
  stage: review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://glance-staging.cern.ch/releases/$CI_ENVIRONMENT_SLUG
    on_stop: stop-review-app
    auto_stop_in: 1 week
  variables:
    GIT_STRATEGY: none
    NEW_RELEASE_FOLDER: $CI_ENVIRONMENT_SLUG
  tags:
    - glance-staging
    - glance-deploy
  script:
    - $STAGING_RELEASES_PATH/bin/create-folders-structure.sh
    - $STAGING_RELEASES_PATH/bin/build-staging-release.sh
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_NAME =~ /^release-.*/
    - if: $CI_COMMIT_TAG =~ /^release-.*/

stop-review-app:
  stage: review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  variables:
    GIT_STRATEGY: none
    TARGET_REVIEW_PATH: "$STAGING_RELEASES_PATH/$CI_ENVIRONMENT_SLUG"
  tags:
    - glance-staging
    - glance-deploy
  script:
    - rm -rf $TARGET_REVIEW_PATH
  when: manual
